GUI/web/web/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include
from django.http import HttpResponse

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", lambda request: HttpResponse("support -> <url>/weibo/ for now")),

    path("weibo/", include("weibo.urls")),
]

GUI/web/weibo/urls.py
from django.urls import path

# from django.http import HttpResponse

from . import views

from django.shortcuts import render


app_name = 'weibo'
urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add, name="add"),

    path("crawler/", views.crawler, name="crawler"),

    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/crawl_and_display/",
         views.crawl_and_display, name="crawl_and_display"),

    #
    # API
    #
    path("get/Seq2SeqPost/", views.get_Seq2SeqPost, name="get_Seq2SeqPost"),
    path("<int:pk>/get/seq2seqpost/<int:index>/",
         views.get_seq2seqpost, name="get_seq2seqpost"),

    #
    # for test at earlier develop.
    #
    # path("test_crawler/", views.test_crawler, name="test_crawler"),
    # path("practise_js/",
    #      lambda request: render(request, "weibo/practise_js.html", {}))
]

GUI/web/weibo/models.py
from django.db import models

# Create your models here.
from django.utils import timezone

import reprlib


class Weibo(models.Model):
    weiboID = models.CharField(max_length=200)
    name = models.CharField(max_length=200)

    def __repr__(self):
        return "{!r}".format(self.name)

    def __str__(self):
        return self.name


class Post(models.Model):
    from_id = models.ForeignKey(Weibo, on_delete=models.CASCADE)
    pub_date = models.DateTimeField("date published", default=timezone.now)
    hashtag = models.CharField(max_length=200, default='')
    text = models.TextField()

    def __repr__(self):
        return "%s" % reprlib.repr(self.text)


class Seq2SeqPost(models.Model):
    from_id = models.ForeignKey(Weibo, on_delete=models.CASCADE)
    pub_date = models.DateTimeField("date published", default=timezone.now)
    hashtag = models.CharField(max_length=200, default='')
    text = models.TextField()

    abstract = models.CharField(max_length=512)

    def __init__(self, *args, **kw):
        super(Seq2SeqPost, self).__init__(*args, **kw)
        self.body = self.text

    def __repr__(self):
        return "%s" % reprlib.repr(self.abstract)

    def __eq__(self, other):
        if not isinstance(other, Seq2SeqPost):
            return NotImplemented
        return str(self.from_id) == str(other.from_id) and \
               self.abstract == other.abstract

GUI/web/weibo/views.py
from django.shortcuts import render

# Create your views here.
import sys
import os
from time import sleep
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.http import Http404
from django.http import JsonResponse

from .models import Weibo, Seq2SeqPost
import re
import copy


def index(request):
    return render(request, "weibo/index.html",
                  {'weibo_all_objects': Weibo.objects.all(), },
                  )


def add(request):
    if request.method == 'POST':
        data = request.POST.get("new_crawl_target", None)
        result = re.findall("^id: (.*) & name: (.*)$", data)
        if not request:
            return HttpResponse("wrong format")
        else:
            weiboID = result[0][0]
            weibo_name = result[0][1]
            try:
                Weibo.objects.create(weiboID=weiboID, name=weibo_name)
                new_target = Weibo.objects.get(weiboID=weiboID)
                return redirect("/" + "weibo" + "/")
                #                      ~~~~~     ~~~~
                #                       ^ sync     ^ index page
                #                   with app_name
            except Exception as err:
                print("Exception: ", err, file=sys.stderr)
                raise


class CrawlResponse404(Exception):
    pass


def do_crawl(weiboID):
    from threading import Thread
    import sites.weibo.request as cweibo  # Reference to > "package path" part
    weibo_crawl = cweibo.WeiboSpider("https://www.weibo.com/%s" % weiboID)
    t = Thread(target=weibo_crawl.run, args=(weibo_crawl.qdata, ))
    t.setDaemon(True)
    t.start()
    del t

    sleep(20)
    weibo_obj = None
    new_post = 0
    for post in weibo_crawl.consumer(weibo_crawl.qdata):
        try:
            weibo_obj = Weibo.objects.get(weiboID=weiboID)
        except Weibo.DoesNotExist:
            raise CrawlResponse404("WeiboID: %s does not exist" % weiboID)

        data_dict = {}
        noHashTag_rule = re.compile("^【(.*)】(.*)$")
        result = re.findall(noHashTag_rule, str(post))
        if not result:
            hashTag_rule = re.compile('^#(.*)#【(.*)】(.*)$')
            result = re.findall(hashTag_rule, str(post))

            if not result:
                # logging here
                print("unknow format post:\n\t", str(post), file=sys.stderr)
                continue
            else:
                # print("[Debug]", file=sys.stderr)
                # print("\t result ==>>>", result, file=sys.stderr)
                # data_dict["pub_date"]  # not achive yet, use default.
                data_dict["hashtag"] = result[0][0]
                data_dict["text"] = result[0][2]
                data_dict["abstract"] = result[0][1]
                # print("[Debug] data_dict", data_dict, file=sys.stderr)
        else:
            data_dict["text"] = result[0][1]
            data_dict["abstract"] = result[0][0]
        data_dict["from_id"] = weibo_obj

        if not Seq2SeqPost.objects.filter(abstract=data_dict["abstract"]):
            seq2seqpost = Seq2SeqPost()
            for key in data_dict.keys():
                setattr(seq2seqpost, key, data_dict[key])
            seq2seqpost.save()
            new_post += 1
        else:
            continue
    if weibo_obj:
        return "%d" % new_post
    else:
        raise CrawlResponse404("server busy")  # raise Http404 should be work!


def crawler(request):
    '''do crawler
      receive crawler weibo id name name

      do crawl, storage crawl to DB

      response 'status', 'crawl number of posts', 'this times start id on DB';
    '''
    if request.method == 'GET':
        try:
            _name = request.GET["name"]
        except Exception as e:
            print("TODO: more specify", e, file=sys.stderr)
            import traceback; traceback.print_exc();
            raise Http404("need specify name")
        else:
            try:
                print("crawler name: ", _name, file=sys.stderr)
                _target = Weibo.objects.get(name=_name)
                return HttpResponse(do_crawl(_target.weiboID))
            except Weibo.DoesNotExist:
                raise Http404(
                    "dose not exist this weibo name in DB, "
                    "please add it on Index page, then request again")
            except CrawlResponse404 as err:
                raise Http404("{}".format(err))
            except Exception as err:
                import traceback; traceback.print_exc();
                raise Http404("{}".format(err))


def crawl_and_display(request, pk):
    # ~~                                                     Browser
    #  ^------------------------------ return HTML ---------->  #
    #                                                          /|
    # views. <--- "weibo/crawler/"  <--- Ajax request  ------#  |
    # crawler()                                              *  /
    # run          API                                       * /
    # in           "weibo/get_seq2seqpost/"  <-- Ajax request -
    # backend!     to get "new" post one by one(and display) *  \
    #                |                                       *   |
    # views.          `--- response seq2seqpost by json -------> #
    # crawler()                                              *
    # finish work, ----- and response! --------------------> #
    #                                          got "weibo/crawler/" response,
    #                                          set MAX length to stop
    #                                          request "weibo/get_seq2seqpost/"
    #
    # mainly logical on crawl_and_display.html with crawler()
    #
    obj = get_object_or_404(Weibo, pk=pk)
    return render(request, "weibo/crawl_and_display.html",
                  {"Weibo_by_pk": obj,
                   "posts_current_number": len(obj.seq2seqpost_set.all())})


def get_Seq2SeqPost(request):
    if request.method == "GET":
        try:
            _weiboID = request.GET["weiboID"]
            _index = request.GET["index"]

            _obj = Weibo.objects.get(weiboID=_weiboID).seq2seqpost_set.all()[int(_index)]
            return HttpResponse(
                "<h1>" + _obj.abstract + "</h1>" +
                "<p><i>" + _obj.hashtag + "</i></p>" +
                "<p>" + _obj.text + "</p>"
            )
        except TypeError:  # "_index" must be integer
            raise
        except IndexError:
            raise
        except Weibo.DoesNotExist:
            return HttpResponse("dose not exist")
        except Seq2SeqPost.DoesNotExist:
            raise


def get_seq2seqpost(request, pk, index):
    """ 'weibo/<weiboID>/get/seq2seqpost/<index>/'
      Response by json!
    """
    if request.method == "GET":
        try:
            seq2seqpost_obj = get_object_or_404(Weibo, pk=pk).seq2seqpost_set.all()[index]

            fix_data = {"eliminate": ["_state", 'from_id_id', "id", ],  # don't include those data
                        "extra": ["weiboID_of_from_id", ],  # extra data
                        }
            data = dict(zip(  # cover object to string
                copy.deepcopy([_key for _key in seq2seqpost_obj.__dict__.keys()]),
                copy.deepcopy([str(getattr(seq2seqpost_obj, _)) for _ in seq2seqpost_obj.__dict__.keys()]),
            ))
            # do the action of fix
            for __k in fix_data["eliminate"]: data.pop(__k)
            for __k in fix_data["extra"]:
                if __k == "weiboID_of_from_id":
                    data[__k] = seq2seqpost_obj.from_id.weiboID
                # elif ...: <= example for expand

            # print(data, file=sys.stderr)
            return JsonResponse(data)
        except (Seq2SeqPost.DoesNotExist, IndexError):
            raise Http404("index Seq2SeqPost Dose not exist")
    else:
        return HttpResponse("wrong request, please use GET")
    return HttpResponse("weibo pk: %d, seq2seqpost index: %d" % (pk, index))


def detail(request, pk):
    """-[o] update this and *.html that
      display one by one by Ajax.
    """
    weibo_obj = get_object_or_404(Weibo, pk=pk)
    try:
        return render(request, "weibo/detail.html",
                      {"weibo_obj": weibo_obj})
    except Exception:
        raise


def test_crawler(request):
    from threading import Thread
    import sites.weibo.request as cweibo  # Reference to > "package path" part
    test_weibo_id = "https://www.weibo.com/58371?topnav=1&wvr=6&topsug=1"
    test_weibo = cweibo.WeiboSpider(test_weibo_id)
    t = Thread(target=test_weibo.run, args=(test_weibo.qdata, ))
    t.setDaemon(True)
    t.start()
    del t

    sleep(50)

    for post in test_weibo.consumer(test_weibo.qdata):
        weibo_id = '58371'
        try:
            weibo_id = Weibo.objects.get(weiboID=weibo_id)
        except Weibo.DoesNotExist:
            weibo_id = Weibo.objects.create(weiboID=weibo_id)

        data_dict = {}
        noHashTag_rule = re.compile("^【(.*)】(.*)$")
        result = re.findall(noHashTag_rule, str(post))
        if not result:
            hashTag_rule = re.compile('^#(.*)#【(.*)】(.*)$')
            result = re.findall(hashTag_rule, str(post))

            if not result:
                # logging here
                print("unknow format post:\n\t", str(post), file=sys.stderr)
                continue
            else:
                print("[Debug]", file=sys.stderr)
                print("\t result ==>>>", result, file=sys.stderr)
                data_dict["from_id"] = weibo_id
                # data_dict["pub_date"]  # not achive yet, use default.
                data_dict["hashtag"] = result[0][0]
                data_dict["text"] = result[0][2]
                data_dict["abstract"] = result[0][1]
                print("[Debug] data_dict", data_dict, file=sys.stderr)
        else:
            data_dict["from_id"] = weibo_id
            data_dict["text"] = result[0][1]

GUI/web/weibo/templates/weibo/bootstrapbase.html
{# weibo/templates/weibo/bootstrapbase.html #}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" media="screen"
        href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">

    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>

    <title>{% block title_text %}{% endblock %}</title>

{% block js_in_head %}  
{% endblock js_in_head %}

  </head>
  <body>
    {% block body %}
    {% endblock %}
  </body>
</html>

GUI/web/weibo/templates/weibo/crawl_and_display.html
{# web/weibo/templates/weibo/detail.html #}
{% extends 'weibo/bootstrapbase.html' %}

	{% block title_text %}Crawl Weibo ID | Weibo{% endblock %}

{% block js_in_head %}
<script >
/**
 * utils function:
 */
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
    /* example */
    async function log_wait_log() {
        console.log("start sleep");
        await sleep(3000);
        console.log("finish sleep");
    }
    /* run for test */
    //log_wait_log();

	var g_crawler_finish_flag = false;
	var crawler_result_new_posts_total = -1;
	var g_seq2seqpost_current_total = {{ posts_current_number }};
</script>
{% endblock js_in_head %}

{% block body %}
<div class="container">
	<div class="row">
		<div class="col-md-12 push-md-4 jumbotron">
		<div class="text-center">
		<h1>{{ Weibo_by_pk.name }}</h1>
		<input type="hidden" name="weibo_DB_id" value="{{ Weibo_by_pk.id }}">
		</div>
		</div>
	</div>
	<div class="row">
	<div class="col-md-12 push-md-4">
		<div class="list-group"
			 name="crawl_result_list" id="crawl_result_list">
		</div>
	</div>
	</div>
</div>

<script>
	function test_request_crawler(_name){
		alert("now, start request crawler with name:" + _name);
		var xmlhttp;
	    xmlhttp = new XMLHttpRequest();

		xmlhttp.open("GET", "/weibo/crawler/?name=" + _name, true);
		xmlhttp.send();
		xmlhttp.onreadystatechange=function(){
			if (xmlhttp.readyState==4 && xmlhttp.status==200){
				g_crawler_finish_flag = true;
				// console.log("xmlhttp.responseText: " + xmlhttp.responseText);
				crawler_result_new_posts_total = parseInt(xmlhttp.responseText);
				// console.log("crawler_result_new_posts_total: " + crawler_result_new_posts_total);
				// console.log("crawler finish!");
			}else if(xmlhttp.status==404){
				alert(xmlhttp.responseText);
			}else{
				// window.location.reload(); // -[o] update later.
 				//alert(xmlhttp.responseText);
			}
		}
	}
	test_request_crawler("{{ Weibo_by_pk.name }}");

	
	async function delay_repeat_request_result(_time){
		await sleep(_time);
		rst = g_seq2seqpost_index - g_seq2seqpost_current_total;
		if ((g_crawler_finish_flag == false) ||
			(rst != crawler_result_new_posts_total)){
			request_crawler_result_one_by_one()
		}
	}

	var g_seq2seqpost_index = g_seq2seqpost_current_total;
	function request_crawler_result_one_by_one(){
		var xmlhttp_OneByOne;
	    xmlhttp_OneByOne = new XMLHttpRequest();

		xmlhttp_OneByOne.open("GET",
			`/weibo/{{ Weibo_by_pk.id }}/get/seq2seqpost/${g_seq2seqpost_index}/`, true);
		xmlhttp_OneByOne.send();
		xmlhttp_OneByOne.onreadystatechange=function(){
			if (xmlhttp_OneByOne.readyState==4 && xmlhttp_OneByOne.status==200){
				var _data = xmlhttp_OneByOne.responseText
				var obj = JSON.parse(_data);

				var _append = "<a href=\"#\" class=\"list-group-item list-group-item-action flex-column align-items-start\">" +
							  "<div class=\"d-flex w-100 justify-content-between\">" +
							  "<h5 class=\"mb-1\">" + obj.abstract + "</h5>" +
							  "<small>" + obj.pub_date + "</small>" +
							  "</div>" +
							  "<small>" + obj.hashtag + "</small>" +
							  "<p class=\"mb-1\">" + obj.text + "</p>" +
							  "</a>"
				document.getElementById("crawl_result_list").innerHTML += _append;
				// $(#"crawl_result_list").after(_append);
				g_seq2seqpost_index += 1;
				delay_repeat_request_result(500);
			}else if(xmlhttp_OneByOne.status==404){
				alert(xmlhttp_OneByOne.responseText);
				delay_repeat_request_result(2000);
			}else{
 				//alert(xmlhttp_OneByOne.responseText);
			}
		}
	}
	delay_repeat_request_result(35000);
</script>
{% endblock body %}

GUI/web/weibo/templates/weibo/detail.html
{# web/weibo/templates/weibo/detail.html #}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link rel="stylesheet" media="screen"
		  href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css"
    	  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
		  crossorigin="anonymous">

	<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js"
	        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
	        crossorigin="anonymous"></script>
	<script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js"
	        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
	        crossorigin="anonymous"></script>
	<script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js"
	        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
	        crossorigin="anonymous"></script>

	<title>Weibo ID Detail | Weibo</title>
</head>
<body>
	<div class="container">
	<div class="row">
		<div class="col-md-12 push-md-4 jumbotron">
		<div class="text-center">
		<h1>{{ weibo_obj.name }}</h1>
		<input type="hidden" name="weibo_DB_id" value="{{ weibo_obj.id }}">
		</div>
		<br/>

		</div>
	</div>
	<div class="row">
	<div class="col-md-12 push-md-4">
		<div class="list-group">
		{% for seq2seqpost in weibo_obj.seq2seqpost_set.all %}
			<a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
				<div class="d-flex w-100 justify-content-between">
					<h5 class="mb-1">{{ seq2seqpost.abstract }}</h5>
					<small>{{ seq2seqpost.pub_date }}</small>
				</div>
				<small>{{ seq2seqpost.hashtag }}</small>
				<p class="mb-1">{{ seq2seqpost.body }}</p>
			</a>
		{% endfor %}
		</div>
	</div>
	</div>
</body>
</html>

GUI/web/weibo/templates/weibo/index.html
{# web/weibo/templates/weibo/index.html #}
{% extends 'weibo/bootstrapbase.html' %}

	{% block title_text %}IDs list on DB | Weibo {% endblock %}

{% block js_in_head %}  
{% endblock js_in_head %}

{% block body %}
	<div class="container">
	<div class="row">
		<div class="col-md-12 push-md-4 jumbotron">
		<div class="text-center">
		<h1>Weibo IDs list</h1>
		</div>
		<br/>

		<form method="POST" action="{% url 'weibo:add' %}">
			<input id="id_new_crawl_target" name="new_crawl_target" 
					placeholder="Enter an weibo id & name to be crawled"
					class="form-control input-lg">

			{% csrf_token %}
		</form>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 push-md-4">
		<table name="id_list_table" id='id_list_table'
		       class="table table-hover">
		    <thead>
			<tr><th>DB index</th>
				<th>Weibo Name</th><th>Action</th></tr>
			</thead>
			<tbody>
		{% for each_weibo in weibo_all_objects %}
			<tr><th scope="row">{{ each_weibo.id }}</th>
				<td><a href="{% url 'weibo:detail' each_weibo.id %}"
					   class="">
				{{ each_weibo.name }}</a>
				</td>
				<td><input type="button" class="btn btn-primary" 
					       name="crawler" id="crawler" value="Crawl"
					       onclick="crawler({{ each_weibo.pk }})"></td>
					       {# onclick="window.open('{% url 'weibo:crawl_and_display' each_weibo.pk %}')"></td> #}
			</tr>
		{% endfor %}
			</tbody>
		</table>
		<script>
			function crawler(_pk){
				var _url = `/weibo/${_pk}/crawl_and_display/`
				window.open(_url);
			}
		</script>
		</div>
	</div>
{% endblock body %}